### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by dev-optimap** [WibuSyariah/optimap-server#1]
@WibuSyariah  Tambahkan beberapa penjelasan pada **README.md** terkait :
- Penjelasan tentang sistem yang dibangun
- System requirements
- Installation Instructions
- Endpoint

**Comment by WibuSyariah** [comment]
README.md dan API-Documentation sudah ditambahkan, check di commit https://github.com/WibuSyariah/optimap-server/commit/4688c6b0b45dd5e7923ef45c6c57217658547e4e, terimakasih
