### ISSUE TITLE
Return format

### ISSUE THREAD

**Issue by dev-optimap** [WibuSyariah/optimap-server#2]
Standar return format : 
- JSON format
- Minimal terdiri dari object **messages**, contoh : 
```
{
   "message": "User registered successfully"
}
```

![image](https://user-images.githubusercontent.com/109659221/180110095-4ffb3743-dbba-4737-b9e4-9bc5f2f7ca47.png)

**Comment by WibuSyariah** [comment]
I've changed the return format, check on this commit: https://github.com/WibuSyariah/optimap-server/commit/604dc9908dbdf3d8ea8699a8cf0b219ff8535c7e thanks
