### ISSUE TITLE
Gagal create profiles karena kesalahan dokumentasi

### ISSUE THREAD

**Issue by dev-optimap** [WibuSyariah/optimap-server#3]
Perbedaan dokumentasi dengan kodingan :
![image](https://user-images.githubusercontent.com/109659221/180394392-f99d4cd5-da0e-4b4e-b546-56d8d572516e.png)
![image](https://user-images.githubusercontent.com/109659221/180394461-64a82ecf-aaa9-4f7f-8c4d-5ac190d8ca72.png)

Menyebabkan error :
![image](https://user-images.githubusercontent.com/109659221/180394535-bad7b157-20cc-47d2-b83d-84a00cefd982.png)

**Comment by WibuSyariah** [comment]
Sudah saya perbaiki, cek di https://github.com/WibuSyariah/optimap-server/commit/37b618ccb9095e5dad67c241b616c01677f5f4d8
