### ISSUE TITLE
Attribute media menggunakan full path url

### ISSUE THREAD

**Issue by dev-optimap** [WibuSyariah/optimap-server#4]
![image](https://user-images.githubusercontent.com/109659221/180394951-c4792450-fd50-490c-8fcd-1a174b0bcb6c.png)
Lengkapi attribute value `photo` dengan Dynamic Hostname / Base URL agar FE bisa langsung memanfaatkan

**Comment by WibuSyariah** [comment]
attribute value photo nya Sudah saya ubah, cek di commit https://github.com/WibuSyariah/optimap-server/commit/7a584bfc03163accb89215bd0ec0d5b617ad38fa

**Comment by dev-optimap** [comment]
Ini baiknya masukin `.env` @WibuSyariah

**Comment by WibuSyariah** [comment]
BASE_URL sudah di pindahkan ke .env, README juga sudah di update, cek di commit https://github.com/WibuSyariah/optimap-server/commit/4c985065c06f80dc690d4075c43dbbd516203646
